'use client'

import { motion } from 'framer-motion'
import { Search, CreditCard, BookOpen, Star, Sparkles, Brain, MessageSquare, Bookmark } from 'lucide-react'

const steps = [
  {
    title: 'Choose Subscription',
    description: 'Select the ChatBook Pro plan that suits you and join the elite community.',
    icon: Sparkles,
    color: 'from-blue-600 to-cyan-500'
  },
  {
    title: 'AI Analysis',
    description: 'Receive deep insights and summaries generated by AI for every book you read.',
    icon: Brain,
    color: 'from-purple-600 to-pink-500'
  },
  {
    title: 'Community Feed',
    description: 'Share your thoughts and interact with elite readers from around the world.',
    icon: MessageSquare,
    color: 'from-orange-500 to-red-600'
  },
  {
    title: 'Personalized Library',
    description: 'Build your collection and track your reading journey with advanced stats.',
    icon: Bookmark,
    color: 'from-green-500 to-emerald-600'
  }
]

export default function HowItWorks() {
  return (
    <section className="py-20 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-20">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-6xl font-black text-white mb-6 tracking-tighter"
          >
            HOW IT <span className="text-blue-500 italic">WORKS</span>
          </motion.h2>
          <p className="text-white/40 text-lg uppercase tracking-[0.3em] font-bold">The Elite Reading Experience</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {steps.map((step, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className="text-center"
            >
              <div className="bg-white rounded-full p-4 w-20 h-20 mx-auto mb-6 flex items-center justify-center shadow-lg">
                <step.icon className="w-10 h-10 text-blue-600" />
              </div>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                {step.title}
              </h3>

              <p className="text-gray-600 leading-relaxed">
                {step.description}
              </p>

              {index < steps.length - 1 && (
                <div className="hidden lg:block absolute top-10 left-full w-full">
                  <div className="flex items-center justify-center">
                    <div className="w-8 h-0.5 bg-blue-200"></div>
                    <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  </div>
                </div>
              )}
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="text-center mt-16"
        >
          <div className="bg-blue-600 rounded-lg p-8 max-w-4xl mx-auto">
            <h3 className="text-2xl font-bold text-white mb-4">
              Ready to Start Reading?
            </h3>
            <p className="text-blue-100 mb-6 text-lg">
              Join thousands of readers who have already discovered their next favorite book.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition-colors">
                Browse Books
              </button>
              <button className="border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-blue-600 transition-colors">
                Create Account
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
